version 1.0
1nadequacy/raccoochat pull request #2
Opened 2017-01-13 19:03 UTC by 1nadequite

RaccooChat Version 1.0.
Was realized multithread server. Was implemented function that makes a query every second on the server and gets all the new messages. All messages are stored in an array. And all users and positions of the last message that this user is got, also are stored in an array.

And also was implemented these functions:
- get all command that we can use in the chat (/command);
- connect and disconnect users;
- it is possible to look who is online now (/users);
- get last five message from the chat (/last).

2017-01-13 19:39 UTC, denisyarats requested changes

2017-01-13 19:39 UTC, 1nadequacy commented on PythonClient.py
> +        print '[' + msg.time + ']' + (' ' * shift) + msg.user_name + ' : ' + msg.text
use formatting here, like print '%s ... ' % (...)

2017-01-13 19:39 UTC, 1nadequacy commented on PythonClient.py
> +    print 'Users online: ' + ', '.join(map(str, usersArray))
same here

2017-01-13 19:39 UTC, 1nadequacy commented on PythonClient.py
> +    transport = TSocket.TSocket('localhost', 9090)
create a separate class for the client and put it in a separate file. develop it's interface.

2017-01-13 19:39 UTC, 1nadequacy commented on PythonClient.py
> +    transport = TSocket.TSocket('localhost', 9090)
pass host and port as binary arguments, you can use argparse for this https://docs.python.org/3/library/argparse.html

2017-01-13 19:39 UTC, 1nadequacy commented on PythonClient.py
> +        user_nickname = raw_input("Input your nickname: ")
please follow google python style guide: https://google.github.io/styleguide/pyguide.html

2017-01-13 19:39 UTC, 1nadequacy commented on gen-cpp/CppRacconChat.h
> +#include "RacconChat.h"
move these files out of gen-cpp. Give it a better name, it shouldn't have Cpp in it. maybe RacoonChatServer or something

2017-01-13 19:39 UTC, 1nadequacy commented on gen-cpp/CppRacconChat.h
> +#include "RacconChat.h"
use #pragma once: read more about it here https://en.wikipedia.org/wiki/Pragma_once

2017-01-13 19:39 UTC, 1nadequacy commented on gen-cpp/CppRacconChat.h
> + private:
usually you define things in the following order:
public:
proteched:
private:

2017-01-13 19:39 UTC, 1nadequacy commented on gen-cpp/CppRacconChat.h
> +  void getLastFiveMessages(std::vector<tutorial::Message>&);
use const for methods if possible, i.e. int f() const;

2017-01-13 19:39 UTC, 1nadequacy commented on gen-cpp/CppServer.cpp
> +#include <thrift/protocol/TBinaryProtocol.h>
the file with the main function, you can call it just server.cpp

2017-01-13 19:39 UTC, 1nadequacy commented on gen-cpp/CppServer.cpp
> +#include <thrift/server/TServer.h>
use include order like this:

#include <files from your library>
...
<empty line>
#include <files from the standard library>
...
<empty line>
#inlcude <files from the other libraries>
...

2017-01-13 19:39 UTC, 1nadequacy commented on gen-cpp/CppServer.cpp
> +  int32_t port = 9090;
use google gflags and glog for printing and passing parameters https://github.com/gflags/gflags

2017-01-13 19:39 UTC, 1nadequacy commented on gen-cpp/MakeFile.md
> +all:
make file usually have name Makefile.

Also we need to start using cmake: https://cmake.org/

2017-01-13 19:39 UTC, 1nadequacy commented on gen-py/tutorial/RacconChat-remote
> +#!/usr/bin/env python
if you don't use this file, feel free to delete it

2017-01-13 19:39 UTC, 1nadequacy commented on tutorial.thrift
> +namespace cpp tutorial
get a better name for the namespace, maybe raccoochat

2017-01-13 19:39 UTC, 1nadequacy commented on tutorial.thrift
> +typedef i32 MyInteger
don't need this typedef, remove

2017-01-13 19:39 UTC, 1nadequacy commented on tutorial.thrift
> +const map<string, string> MAP_COMMAND = {'users': '/users - returns all users that are online.',
format this map:
map = {
  k: v,
  k: v,
}

2017-01-13 19:39 UTC, 1nadequacy commented on tutorial.thrift
> +  1: string time,
use c++ style guide here

2017-01-14 14:07 UTC, 1nadequite commented on PythonClient.py
> +        print '[' + msg.time + ']' + (' ' * shift) + msg.user_name + ' : ' + msg.text
done

2017-01-14 14:07 UTC, 1nadequite commented on PythonClient.py
> +    print 'Users online: ' + ', '.join(map(str, usersArray))
done

2017-01-14 14:07 UTC, 1nadequite commented on PythonClient.py
> +        user_nickname = raw_input("Input your nickname: ")
done

2017-01-14 14:08 UTC, 1nadequite commented on gen-cpp/CppRacconChat.h
> +#include "RacconChat.h"
the same error
![image](https://cloud.githubusercontent.com/assets/13332523/21955423/00402bb4-da7c-11e6-950f-85ad3ef46b20.png)

2017-01-14 14:08 UTC, 1nadequite commented on gen-cpp/CppRacconChat.h
> +#include "RacconChat.h"
done

2017-01-14 14:08 UTC, 1nadequite commented on gen-cpp/CppRacconChat.h
> + private:
done

2017-01-14 14:08 UTC, 1nadequite commented on gen-cpp/CppServer.cpp
> +#include <thrift/protocol/TBinaryProtocol.h>
done

2017-01-14 14:09 UTC, 1nadequite commented on gen-cpp/CppServer.cpp
> +#include <thrift/server/TServer.h>
what do you mean?

2017-01-14 14:09 UTC, 1nadequite commented on gen-py/tutorial/RacconChat-remote
> +#!/usr/bin/env python
done

2017-01-14 14:09 UTC, 1nadequite commented on tutorial.thrift
> +namespace cpp tutorial
done

2017-01-14 14:09 UTC, 1nadequite commented on tutorial.thrift
> +typedef i32 MyInteger
done

2017-01-14 14:10 UTC, 1nadequite commented on tutorial.thrift
> +const map<string, string> MAP_COMMAND = {'users': '/users - returns all users that are online.',
done

2017-01-14 14:10 UTC, 1nadequite commented on tutorial.thrift
> +  1: string time,
done

2017-01-14 14:11 UTC, 1nadequite commented on PythonClient.py
> +    transport = TSocket.TSocket('localhost', 9090)
don't understand how it works

2017-01-14 17:06 UTC, 1nadequacy commented on PythonClient.py
> +    transport = TSocket.TSocket('localhost', 9090)
Here is an example:
`
parser = argparse.ArgumentParser(description='freq map')
parser.add_argument('--input', help='input file')
parser.add_argument('--output', help='output file')
args = parser.parse_args()
`

then you can call you binary like this
`
./binary --input name_of_input_file --output name_of_output_file
`

2017-01-14 17:14 UTC, 1nadequacy commented on gen-cpp/CppRacconChat.h
> +#include "RacconChat.h"
what compiler do you use? llvv-g++?

2017-01-14 17:15 UTC, 1nadequacy commented on gen-cpp/CppServer.cpp
> +#include <thrift/server/TServer.h>
updated the comment

2017-01-14 17:15 UTC, 1nadequite commented on gen-cpp/CppRacconChat.h
> +#include "RacconChat.h"
yes

2017-01-16 18:29 UTC, 1nadequite commented on gen-cpp/CppServer.cpp
> +#include <thrift/server/TServer.h>
done.

2017-01-16 18:30 UTC, 1nadequite commented on PythonClient.py
> +    transport = TSocket.TSocket('localhost', 9090)
There is a problem with thrift.

2017-01-16 18:30 UTC, 1nadequite commented on PythonClient.py
> +    transport = TSocket.TSocket('localhost', 9090)
done

2017-01-16 18:30 UTC, 1nadequite commented on gen-cpp/CppRacconChat.h
> +  void getLastFiveMessages(std::vector<tutorial::Message>&);
done

2017-01-16 18:31 UTC, 1nadequite commented
RaccooChat Version 1.1.
Last changes:
  - test_gflag.cpp - c++ file for testing gflag and glog;
 Client.py was divided on two separate files:
  - client.py - client;
  - RaccooChatClient.py - class for working with server;

2017-01-16 18:46 UTC, denisyarats approved these changes

2017-01-16 18:46 UTC, merged