Version 1.1.1
1nadequacy/raccoochat pull request #5
Opened 2017-01-17 11:00 UTC by 1nadequite

2017-01-19 17:51 UTC, denisyarats approved these changes

2017-01-19 17:55 UTC, denisyarats requested changes

2017-01-19 17:55 UTC, 1nadequacy commented on raccoochat/RaccooChatClient.py
> +            shift = 10 - len(message.userName)
what if user name is longer than 10?

2017-01-19 17:55 UTC, 1nadequacy commented on raccoochat/RaccooChatServer.cpp
> +  int32_t currectUserId = usersOnline_[username].userId;
const int32_t

2017-01-19 17:55 UTC, 1nadequacy commented on raccoochat/RaccooChatServer.cpp
> +  std::vector<raccoochat::SimpleMessage> userMessages = privateMessages_[currectUserId];
const auto&

2017-01-19 17:55 UTC, 1nadequacy commented on raccoochat/RaccooChatServer.cpp
> +  int32_t currentUserId = usersOnline_[username].userId;
const int32_t

2017-01-19 17:55 UTC, 1nadequacy commented on raccoochat/gen-cpp/RaccooChat_server.skeleton.cpp
> +// This autogenerated skeleton file illustrates how to build a server.
remove this file

2017-01-19 17:55 UTC, 1nadequacy commented on CMakeCache.txt
> +# This is the CMakeCache file.
You committed all these temporary crap from cmake. next time clean this shit.
just create a shell script like cleanup.sh where you remove all these temporary folders

2017-01-19 18:04 UTC, 1nadequite commented on raccoochat/RaccooChatClient.py
> +            shift = 10 - len(message.userName)
i am working now on keeping users and passwords in a file.
This function will be changed.

2017-01-21 16:08 UTC, 1nadequite commented on raccoochat/RaccooChatServer.cpp
> +  int32_t currectUserId = usersOnline_[username].userId;
done

2017-01-21 16:09 UTC, 1nadequite commented on raccoochat/RaccooChatServer.cpp
> +  std::vector<raccoochat::SimpleMessage> userMessages = privateMessages_[currectUserId];
done

2017-01-21 16:09 UTC, 1nadequite commented on raccoochat/RaccooChatServer.cpp
> +  int32_t currentUserId = usersOnline_[username].userId;
done

2017-01-21 16:09 UTC, 1nadequite commented on CMakeCache.txt
> +# This is the CMakeCache file.
created cleanup.sh

2017-01-21 19:05 UTC, merged